version: '3'
services:

  # The Application
  app:
    build:
      context: .
      dockerfile: ./web/app.dockerfile
    volumes:
      - ./web/app/:/srv/app/web/app
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
      - ./web/app/storage:/srv/app/web/app/storage
      - ./web/app/storage:/srv/app/web/app/bootstrap/cache

  # The Web Server
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    volumes:
      - ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
      - ./web/app/public:/srv/app/web/app/public:rw
      - ./web/app/storage:/srv/app/web/app/storage:rw
    ports:
      - 8443:443
    depends_on:
      - app
  # The Database
  database:
    image: mariadb:10.4.12
    volumes:
      - ./docker/db/dbdata:/var/lib/mysql:rw
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: tom_money_management
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: tom
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=tom
      - PMA_PASSWORD=123456
    ports:
      - 8444:80
    depends_on:
      - database
volumes:
  dbdata: {}
