version: '3'
services:

  # The Application
  app:
    build:
      context: ./web
      dockerfile: app.dockerfile
    volumes:
      - ./web/app/:/srv/app/web/app:rw

  # The Web Server
  web:
    build:
      context: docker/nginx/
      dockerfile: nginx.dockerfile
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./web/app/public:/srv/app/web/public:rw
    ports:
      - 8080:80
    depends_on:
      - app
  # The Database
  database:
    image: mariadb:10.4.12
    volumes:
      - ./db/dbdata:/var/lib/mysql:rw
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: tom_money_management
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: tom
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=tom
      - PMA_PASSWORD=123456
    ports:
      - 8081:80
    depends_on:
      - database
volumes:
  dbdata:
